name: Gradle Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
    - name: Setup Java
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
    - name: Run Gradle Test
      uses: eskatos/gradle-command-action@v1.4.0
      with:
        arguments: test --stacktrace --debug
