name: Build and Deploy Release Assets

on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
      - name: Checkout Repository
        uses: actions/checkout@4.1.4
      - name: Generate Artifacts
        uses: eskatos/gradle-command-action@v1.4
        with:
          arguments: build
      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: /home/runner/work/chalkbox/chalkbox/build/libs/chalkbox.jar
